### ISSUE TITLE
Помогите какая то странность с авторизацией

### ISSUE THREAD

**Issue by alex290** [carono/yii2-1c-exchange#17]
Помогите. Не могу понять на локальном сервере все нормально на удаленном не проходит авторизацию

yii\web\HttpException:401

`	yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure()
#1 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/ActionFilter.php(77): yii\filters\auth\AuthMethod->beforeAction()
#2 [internal function]: yii\base\ActionFilter->beforeFilter()
#3 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func()
#4 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Controller.php(297): yii\base\Component->trigger()
#5 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/web/Controller.php(219): yii\base\Controller->beforeAction()
#6 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Controller.php(176): yii\web\Controller->beforeAction()
#7 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#8 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#9 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#10 /home/cobaltpro/domains/base.cob-alt.pro/public_html/web/index.php(13): yii\base\Application->run()
#11 {main}`

Я даже не знаю куда копать

**Comment by mazurva** [comment]
Почитай [эту тему](https://github.com/yiisoft/yii2/issues/6631), возможно у тебя этот случай.

**Comment by alex290** [comment]
> Почитай [эту тему](https://github.com/yiisoft/yii2/issues/6631), возможно у тебя этот случай.

Спасибо. Не подумал про  .htaccess

`
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
`
