### ISSUE TITLE
При выгрузке получаю ошибку 500.

### ISSUE THREAD

**Issue by alex290** [carono/yii2-1c-exchange#18]
Помогите разобраться. При выгрузке получаю ошибку 500

Лог ошибок
Error: Class name must be a valid object or a string in /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/carono/yii2-1c-exchange/controllers/ApiController.php:192
Stack trace:
#0 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/carono/yii2-1c-exchange/controllers/ApiController.php(280): carono\exchange1c\controllers\ApiController->parsingImport()
#1 [internal function]: carono\exchange1c\controllers\ApiController->actionImport()
#2 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#4 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#5 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#6 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#7 /home/cobaltpro/domains/base.cob-alt.pro/public_html/web/index.php(13): yii\base\Application->run()
#8 {main}

возможно связанно с версией php8.3

**Comment by mazurva** [comment]
Попробуй снизить PHP до 8.0. Либо попробуй взять не стабильную версию (0.3.1), а из dev-master.

**Comment by alex290** [comment]
> Попробуй снизить PHP до 8.0. Либо попробуй взять не стабильную версию (0.3.1), а из dev-master.

Снизить не получилось а dev версия выдала в другом месте ошибку

Error: Class name must be a valid object or a string in /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/carono/yii2-1c-exchange/controllers/ApiController.php:237
Stack trace:
#0 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/carono/yii2-1c-exchange/controllers/ApiController.php(335): carono\exchange1c\controllers\ApiController->parsingImport()
#1 [internal function]: carono\exchange1c\controllers\ApiController->actionImport()
#2 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#4 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#5 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#6 /home/cobaltpro/domains/base.cob-alt.pro/public_html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#7 /home/cobaltpro/domains/base.cob-alt.pro/public_html/web/index.php(13): yii\base\Application->run()
#8 {main}

И ошибка та же

**Comment by alex290** [comment]
Извиняюсь. Это я ошибся все работает под php 8.3
