### ISSUE TITLE
Не парсит выгруженный архив, удаляет сразу

### ISSUE THREAD

**Issue by ismagilovnail** [carono/yii2-1c-exchange#2]
Все настроено правильно. На локалке работает как надо. Загрузил на сервер, не парсит выгруженный архив или вообще не выгружает удаляет папку в runtime сразу. Смотрел логи от 1с все запросы приходят корректно. 
`
77.242.108.174 - admins [14/Sep/2018:09:58:08 +0300] "GET /1c_exchange.php?type=catalog&mode=checkauth HTTP/1.0" 200 544 "-" "1C+Enterprise/8.3"
77.242.108.174 - admins [14/Sep/2018:09:58:09 +0300] "GET /1c_exchange.php?type=catalog&mode=init HTTP/1.0" 200 528 "-" "1C+Enterprise/8.3"
77.242.108.174 - admins [14/Sep/2018:09:58:10 +0300] "POST /1c_exchange.php?type=catalog&mode=file&filename=v8_1A76_155ae.zip HTTP/1.0" 200 506 "-" "1C+Enterprise/8.3"
77.242.108.174 - admins [14/Sep/2018:09:58:11 +0300] "GET /1c_exchange.php?type=catalog&mode=import&filename=import0_28.xml HTTP/1.0" 200 506 "-" "1C+Enterprise/8.3"`

ошибочных логов нет

После нескольких попыток успешно записаля только 1 кусок архива и офферы к нему

**Comment by carono** [comment]
Расширение для ZIP на сервере установлено? Попробуйте установить параметр в модуле useZip=false, тогда 1С будет слать файлами, возможно поможет, или хотя бы увидим ошибку.

**Comment by carono** [comment]
Так же включите параметр debug=true, файлы из архива не будут удаляться, возможно архив приходит пустой?

**Comment by ismagilovnail** [comment]
ZIP на сервере установлено. Пробовал отключить но так без архивов картинки не передаютс. Подозреваю что то с сессией не так, с определением названий архивов для распаковки

**Comment by ismagilovnail** [comment]
Проблему я примерно понял, архивы грузятсявсе ок, Но extractArchive не срабатывает изза этого -> `$archive = self::getData('archive')) && file_exists($archive) && class_exists('ZipArchive')`
потому что название текущего архива не равен self::getData('archive') и его не существует в каталоге. В итоге скрипт выдает success даже если не парсил и удаляет директорию полностью

![image](https://user-images.githubusercontent.com/25949924/45535848-381e4080-b819-11e8-80d1-d322f60b9b49.png)

**Comment by carono** [comment]
Явно что-то с сессиями не так. Наверно нужно переделать систему распаковки архивов, странно что локально то работает нормально

**Comment by ismagilovnail** [comment]
Может распоковку делать после загрузки архива сразу ?

**Comment by carono** [comment]
Да, я об этом и говорю, но не знаю почему в самом начале так не сделал, возможно были какие то на то причины, которые сейчас не помню.

**Comment by ismagilovnail** [comment]
`if (!self::getData('archive') && strtolower(pathinfo($filePath, PATHINFO_EXTENSION)) === 'zip') {
            self::setData('archive', $filePath);
        }`

в этом куске кода когда загружаетс архив, почему то ты проверяешь на существование архива в сесии и тип приема. А что если предыдущая сессия не удалился, он выдаст тебе true. В итоге названия будут разными при приеме и в сессии. и когда настает время распаковки скрипт не может найти новый архив. Так как в getData старое имя

**Comment by carono** [comment]
Согласен, это узкое место

**Comment by carono** [comment]
Сделал тестовую ветку, подключи версию `composer require carono/yii2-1c-exchange:dev-issues/2-extract-archive` и потестируй, без тестов сразу в мастер лить не могу, придется самому руками тестировать еще

**Comment by carono** [comment]
как успехи?

**Comment by ismagilovnail** [comment]
Проверил. Парсинг идет норм. Но:
1. после парсинга offers не очищает runtime. 
2. Не плохо было бы добавить на проверку существования директории для картинок в FileUploadTrait

**Comment by carono** [comment]
1. офферы очищаю, но там остаются картинки, пока точно не знаю, куда вставить очистку кеша
2. это видимо по этому пакету https://github.com/carono/yii2-file-upload не очень ясно что именно ты хочешь и для чего
