### ISSUE TITLE
Ошибка работы с Интернет: внутренняя ошибка сервера (500)

### ISSUE THREAD

**Issue by Sergeymain** [carono/yii2-1c-exchange#5]
Вот что в логах 1с у меня 
```
Ошибка при выполнении файловой операции  '1c_exchange.php?type=catalog&mode=file&filename=v8_1A25_210.zip&'
по причине:
Ошибка работы с Интернет:  внутренняя ошибка сервера (500).
```

**Comment by Sergeymain** [comment]
А более развернуто по этому пункту можно? 

> 3. Если используете apache как веб сервер, не забудьте создать и настроить .htaccess в web директории

**Comment by Sergeymain** [comment]
Вот что у меня в конфиге apache
```
<VirtualHost 127.0.0.1:8080>
	ServerName dev.super-master.pro
	ServerAlias www.dev.super-master.pro
	DocumentRoot /var/www/main_user/data/www/dev.super-master.pro/web
	ServerAdmin webmaster@dev.super-master.pro
	DirectoryIndex index.php index.html
	AddDefaultCharset off
	AssignUserID main_user main_user
	CustomLog /var/www/httpd-logs/dev.super-master.pro.access.log combined
	ErrorLog /var/www/httpd-logs/dev.super-master.pro.error.log
	<FilesMatch "\.ph(p[3-5]?|tml)$">
		SetHandler application/x-httpd-php
	</FilesMatch>
	<FilesMatch "\.phps$">
		SetHandler application/x-httpd-php-source
	</FilesMatch>
	<IfModule php5_module>
		php_admin_value sendmail_path "/usr/sbin/sendmail -t -i -f webmaster@dev.super-master.pro"
		php_admin_value upload_tmp_dir "/var/www/main_user/data/mod-tmp"
		php_admin_value session.save_path "/var/www/main_user/data/mod-tmp"
		php_admin_value open_basedir "/var/www/main_user/data:."
	</IfModule>
	<IfModule php7_module>
		php_admin_value sendmail_path "/usr/sbin/sendmail -t -i -f webmaster@dev.super-master.pro"
		php_admin_value upload_tmp_dir "/var/www/main_user/data/mod-tmp"
		php_admin_value session.save_path "/var/www/main_user/data/mod-tmp"
		php_admin_value open_basedir "/var/www/main_user/data:."
	</IfModule>
	SetEnvIf X-Forwarded-Proto https HTTPS=on
</VirtualHost>
<Directory /var/www/main_user/data/www/dev.super-master.pro/web>
	Options +Includes -ExecCGI
	<IfModule php5_module>
		php_admin_flag engine on
	</IfModule>
	<IfModule php7_module>
		php_admin_flag engine on
	</IfModule>
</Directory>

<Directory /var/www/main_user/data/www/dev.super-master.pro/web>
	RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . index.php
	php_admin_flag engine on
</Directory>
```

**Comment by Sergeymain** [comment]
А когда перехожу по http://dev.super-master.pro/exchange/article/index
У меня вот какая ошибка:
`Database Exception – yii\db\Exception
could not find driver
↵
Caused by: PDOException
could not find driver
in /var/www/main_user/data/www/dev.super-master.pro/vendor/yiisoft/yii2/db/Connection.php at line 602`

**Comment by Sergeymain** [comment]
Перешел по http://dev.super-master.pro/exchange/
Он у меня открыл документацию...

**Comment by carono** [comment]
> Перешел по http://dev.super-master.pro/exchange/
> Он у меня открыл документацию...

Все верно, там и есть документация.



> Database Exception – yii\db\Exception could not find driver

Для документации, там используется sqlite драйвер, проверь, подключен ли он у тебя, в любом случае, там тоже самое, что и в README, только структурированное

> Ошибка при выполнении файловой операции  '1c_exchange.php?type=catalog&mode=file&filename=v8_1A25_210.zip&'

Вот тут уже нужно смотреть в логи, что именно за ошибка

**Comment by carono** [comment]
> А более развернуто по этому пункту можно?

Тут стандартная настройка для фреймворка, чтобы все запросы шли на index.php, у вас это уже настроено

**Comment by carono** [comment]
> внутренняя ошибка сервера (500).

скиньте лог, runtime/logs/app.log

**Comment by carono** [comment]
Сейчас у вас там ошибка "The identity object must implement IdentityInterface.", значит модель юзера не использует интерфейс IdentityInterface, поправьте это

**Comment by carono** [comment]
с Yii 2.0.10 модуль не работает, нужна последняя версия
