### ISSUE TITLE
Подключение модуля

### ISSUE THREAD

**Issue by Sergiayn** [carono/yii2-1c-exchange#6]
Просьба в классе carono\exchange1c\Bootstrap
строку Yii::$app->urlManager->addRules([new UrlRule]);
заменить на Yii::$app->urlManager->addRules([new UrlRule], false);

Это нужно для того, что бы urlManager менеджер добавлялся не в конце. Например, у меня есть правило ['pattern'=>'<slug>', 'route'=>'page/view'] , которое срабатывает если ничего другого не совпало (для того, что бы можно было создать страницу с произвольным url). Но без второго параметра (в addRules) правило модуля оказывается ниже и не срабатывает

**Comment by carono** [comment]
Выкатил новую версию 2,0,9, по умолчанию привило в начало добавляется теперь, можно через конфиг изменить. Проверь

**Comment by Sergiayn** [comment]
> Выкатил новую версию 2,0,9, по умолчанию привило в начало добавляется теперь, можно через конфиг изменить. Проверь

Теперь все работает как надо. Спасибо за оперативность
