### ISSUE TITLE
classifier.xml

### ISSUE THREAD

**Issue by Sergiayn** [carono/yii2-1c-exchange#7]
Добрый день! При импорте из 1с на файле classifier.xml выдает ошибку что нет гурппы ( в файле действительно группы нет). 
Ошибка возникает в файле Zenwalker\CommerceML\Model\Classifier в методе getGroups. $this->xml->Группы->Группа возвращает null и дальше это приводит к ошибке. 
Можно ли там сделать проверку? Или может я не верно делаю импорт файла classifier.xml ( 1c_exchange.php?type=catalog&mode=import&filename=import___5383e573-3524-4b8c-9585-ad3582aad793.xml )?

**Comment by carono** [comment]
Если нет группы в файле, значит 1С не всё выгружает, нужно на её стороне это смотреть. Файл classifier.xml формируется чисто для технических нужд, он равен классификатору в import.xml

**Comment by Sergiayn** [comment]
А можно поставить проверку наличия группы, что бы не было ошибки? Или лучше решать со стороны 1с?

**Comment by carono** [comment]
Сделал проверку на существование групп, можете обновить пакет `composer update carono/commerceml`

**Comment by Sergiayn** [comment]
Помогло, спасибо
